create table sm_order(
  id serial primary key,
  order_id varchar(255),
  sap_order_type varchar(255),
  sap_order_type_desc varchar(255),
  order_source varchar(255),
  order_item_id varchar(255),
  status_code varchar(255),
  status_desc varchar(255),
  company_name varchar(255),
  cmmdty_qa_type varchar(255),
  operate_item_dec varchar(255),
  created_time varchar(255),
  cmmdty_name varchar(255),
  cmmdty_ctgry_dec varchar(255),
  cmmdty_band_dec varchar(255),
  hope_arrival_time varchar(255),
  operate_time varchar(255),
  service_aptitude_dec varchar(255),
  first_srv_time varchar(255),
  srv_time varchar(255),
  latest_assignmengt_time varchar(255),
  last_alloted_wd varchar(255),
  latest_door_time varchar(255),
  finish_time varchar(255),
  confirm_time varchar(255),
  zyry1_bp varchar(255),
  zyry1_bp_name varchar(255),
  integrated_deli_flag varchar(255),
  service_sale varchar(255),
  wd_name varchar(255),
  account_object varchar(255),
  wd varchar(255),
  json_str text,
    created_at datetime,
updated_at datetime
)